<?php

namespace Database\Seeders;

use App\Models\Municipality;
use App\Models\Province;
use Illuminate\Database\Seeder;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipalities = [
            ["id" => 1, "name" => "La Lisa", "province_id" => 1],
            ["id" => 2, "name" => "Diez de Octubre", "province_id" => 1],
            ["id" => 3, "name" => "Marianao", "province_id" => 1],
            ["id" => 4, "name" => "Playa", "province_id" => 1],
            ["id" => 5, "name" => "Plaza de la Revolución", "province_id" => 1],
            ["id" => 6, "name" => "Boyeros", "province_id" => 1],
            ["id" => 7, "name" => "San Miguel del Padrón", "province_id" => 1],
            ["id" => 8, "name" => "Habana del Este", "province_id" => 1],
            ["id" => 9, "name" => "Arroyo Naranjo", "province_id" => 1],
            ["id" => 10, "name" => "Habana Vieja", "province_id" => 1],
            ["id" => 11, "name" => "Guanabacoa", "province_id" => 1],
            ["id" => 12, "name" => "Regla", "province_id" => 1],
            ["id" => 13, "name" => "Cerro", "province_id" => 1],
            ["id" => 14, "name" => "Centro Habana", "province_id" => 1],
            ["id" => 15, "name" => "Cotorro", "province_id" => 1],
            ["id" => 170, "name" => "La Plata", "province_id" => 1],
            ["id" => 171, "name" => "Mar del Plata", "province_id" => 1],
            ["id" => 172, "name" => "Tandil", "province_id" => 1],
            ["id" => 173, "name" => "Bahía Blanca", "province_id" => 1],
            ["id" => 174, "name" => "San Nicolás", "province_id" => 1],
            ["id" => 175, "name" => "Junín", "province_id" => 1],
            ["id" => 176, "name" => "Pergamino", "province_id" => 1],
            ["id" => 177, "name" => "Azul", "province_id" => 1],
            ["id" => 178, "name" => "Olavarría", "province_id" => 1],
            ["id" => 179, "name" => "Necochea", "province_id" => 1],
            ["id" => 180, "name" => "Tres Arroyos", "province_id" => 1],
            ["id" => 181, "name" => "Campana", "province_id" => 1],
            ["id" => 182, "name" => "Zárate", "province_id" => 1],
            ["id" => 183, "name" => "Luján", "province_id" => 1],
            ["id" => 184, "name" => "Mercedes", "province_id" => 1],
            ["id" => 16, "name" => "Jimagüayú", "province_id" => 2],
            ["id" => 17, "name" => "Sibanicú", "province_id" => 2],
            ["id" => 18, "name" => "Céspedes", "province_id" => 2],
            ["id" => 19, "name" => "Esmeralda", "province_id" => 2],
            ["id" => 20, "name" => "Florida", "province_id" => 2],
            ["id" => 21, "name" => "Guáimaro", "province_id" => 2],
            ["id" => 22, "name" => "Minas", "province_id" => 2],
            ["id" => 23, "name" => "Sierra de Cubitas", "province_id" => 2],
            ["id" => 24, "name" => "Vertientes", "province_id" => 2],
            ["id" => 25, "name" => "Nuevitas", "province_id" => 2],
            ["id" => 26, "name" => "Santa Cruz del Sur", "province_id" => 2],
            ["id" => 27, "name" => "Najasa", "province_id" => 2],
            ["id" => 28, "name" => "Camagüey", "province_id" => 2],
            ["id" => 185, "name" => "Córdoba Capital", "province_id" => 2],
            ["id" => 186, "name" => "Río Cuarto", "province_id" => 2],
            ["id" => 187, "name" => "Villa María", "province_id" => 2],
            ["id" => 188, "name" => "San Francisco", "province_id" => 2],
            ["id" => 189, "name" => "Villa Carlos Paz", "province_id" => 2],
            ["id" => 190, "name" => "Alta Gracia", "province_id" => 2],
            ["id" => 191, "name" => "Jesús María", "province_id" => 2],
            ["id" => 192, "name" => "La Falda", "province_id" => 2],
            ["id" => 193, "name" => "Bell Ville", "province_id" => 2],
            ["id" => 194, "name" => "Marcos Juárez", "province_id" => 2],
            ["id" => 29, "name" => "Florencia", "province_id" => 3],
            ["id" => 30, "name" => "Morón", "province_id" => 3],
            ["id" => 31, "name" => "Majagua", "province_id" => 3],
            ["id" => 32, "name" => "Primero de enero", "province_id" => 3],
            ["id" => 33, "name" => "Chambas", "province_id" => 3],
            ["id" => 34, "name" => "Ciego de Ávila", "province_id" => 3],
            ["id" => 35, "name" => "Ciro Redondo", "province_id" => 3],
            ["id" => 36, "name" => "Baraguá", "province_id" => 3],
            ["id" => 37, "name" => "Bolivia", "province_id" => 3],
            ["id" => 38, "name" => "Venezuela", "province_id" => 3],
            ["id" => 195, "name" => "Santa Fe Capital", "province_id" => 3],
            ["id" => 196, "name" => "Rosario", "province_id" => 3],
            ["id" => 197, "name" => "Rafaela", "province_id" => 3],
            ["id" => 198, "name" => "Reconquista", "province_id" => 3],
            ["id" => 199, "name" => "Venado Tuerto", "province_id" => 3],
            ["id" => 200, "name" => "Esperanza", "province_id" => 3],
            ["id" => 201, "name" => "Villa Gobernador Gálvez", "province_id" => 3],
            ["id" => 202, "name" => "Santo Tomé", "province_id" => 3],
            ["id" => 203, "name" => "Casilda", "province_id" => 3],
            ["id" => 204, "name" => "Firmat", "province_id" => 3],
            ["id" => 39, "name" => "Aguada de Pasajeros", "province_id" => 4],
            ["id" => 40, "name" => "Santa Isabel de las Lajas", "province_id" => 4],
            ["id" => 41, "name" => "Cruces", "province_id" => 4],
            ["id" => 42, "name" => "Cienfuegos", "province_id" => 4],
            ["id" => 43, "name" => "Palmira", "province_id" => 4],
            ["id" => 44, "name" => "Abreus", "province_id" => 4],
            ["id" => 45, "name" => "Rodas", "province_id" => 4],
            ["id" => 46, "name" => "Cumanayagua", "province_id" => 4],
            ["id" => 205, "name" => "Mendoza Capital", "province_id" => 4],
            ["id" => 206, "name" => "San Rafael", "province_id" => 4],
            ["id" => 207, "name" => "Godoy Cruz", "province_id" => 4],
            ["id" => 208, "name" => "Maipú", "province_id" => 4],
            ["id" => 209, "name" => "Luján de Cuyo", "province_id" => 4],
            ["id" => 210, "name" => "Rivadavia", "province_id" => 4],
            ["id" => 211, "name" => "Las Heras", "province_id" => 4],
            ["id" => 212, "name" => "Guaymallén", "province_id" => 4],
            ["id" => 213, "name" => "General Alvear", "province_id" => 4],
            ["id" => 214, "name" => "Tupungato", "province_id" => 4],
            ["id" => 47, "name" => "Manzanillo", "province_id" => 5],
            ["id" => 48, "name" => "Niquero", "province_id" => 5],
            ["id" => 49, "name" => "Yara", "province_id" => 5],
            ["id" => 50, "name" => "Buey Arriba", "province_id" => 5],
            ["id" => 51, "name" => "Bartolomé Masó", "province_id" => 5],
            ["id" => 52, "name" => "Cauto Cristo", "province_id" => 5],
            ["id" => 53, "name" => "Bayamo", "province_id" => 5],
            ["id" => 54, "name" => "Jiguaní", "province_id" => 5],
            ["id" => 55, "name" => "Campechuela", "province_id" => 5],
            ["id" => 56, "name" => "Media Luna", "province_id" => 5],
            ["id" => 57, "name" => "Río Cauto", "province_id" => 5],
            ["id" => 58, "name" => "Pilón", "province_id" => 5],
            ["id" => 59, "name" => "Guisa", "province_id" => 5],
            ["id" => 215, "name" => "San Miguel de Tucumán", "province_id" => 5],
            ["id" => 216, "name" => "Tafí Viejo", "province_id" => 5],
            ["id" => 217, "name" => "Yerba Buena", "province_id" => 5],
            ["id" => 218, "name" => "Concepción", "province_id" => 5],
            ["id" => 219, "name" => "Monteros", "province_id" => 5],
            ["id" => 220, "name" => "Aguilares", "province_id" => 5],
            ["id" => 221, "name" => "Bella Vista", "province_id" => 5],
            ["id" => 222, "name" => "Famaillá", "province_id" => 5],
            ["id" => 223, "name" => "Lules", "province_id" => 5],
            ["id" => 224, "name" => "Trancas", "province_id" => 5],
            ["id" => 60, "name" => "Niceto Perez", "province_id" => 6],
            ["id" => 61, "name" => "Manuel Tames", "province_id" => 6],
            ["id" => 62, "name" => "Maisí", "province_id" => 6],
            ["id" => 63, "name" => "Caimanera", "province_id" => 6],
            ["id" => 64, "name" => "El Salvador", "province_id" => 6],
            ["id" => 65, "name" => "Yateras", "province_id" => 6],
            ["id" => 66, "name" => "San Antonio del Sur", "province_id" => 6],
            ["id" => 67, "name" => "Baracoa", "province_id" => 6],
            ["id" => 68, "name" => "Imías", "province_id" => 6],
            ["id" => 69, "name" => "Guantánamo", "province_id" => 6],
            ["id" => 70, "name" => "Rafael Freyre", "province_id" => 7],
            ["id" => 71, "name" => "Cacocum", "province_id" => 7],
            ["id" => 72, "name" => "Calixto García", "province_id" => 7],
            ["id" => 73, "name" => "Holguín", "province_id" => 7],
            ["id" => 74, "name" => "Banes", "province_id" => 7],
            ["id" => 75, "name" => "Antilla", "province_id" => 7],
            ["id" => 76, "name" => "Báguanos", "province_id" => 7],
            ["id" => 77, "name" => "Sagua de Tánamo", "province_id" => 7],
            ["id" => 78, "name" => "Urbano Noris", "province_id" => 7],
            ["id" => 79, "name" => "Frank País", "province_id" => 7],
            ["id" => 80, "name" => "Mayarí", "province_id" => 7],
            ["id" => 81, "name" => "Gibara", "province_id" => 7],
            ["id" => 82, "name" => "Moa", "province_id" => 7],
            ["id" => 83, "name" => "Cueto", "province_id" => 7],
            ["id" => 84, "name" => "Julio Antonio Mella (Isla de la Juventud)", "province_id" => 8],
            ["id" => 85, "name" => "Isla de la Juventud", "province_id" => 8],
            ["id" => 86, "name" => "Güira de Melena", "province_id" => 9],
            ["id" => 87, "name" => "San Cristóbal", "province_id" => 9],
            ["id" => 88, "name" => "Guanajay", "province_id" => 9],
            ["id" => 89, "name" => "Caimito", "province_id" => 9],
            ["id" => 90, "name" => "Mariel", "province_id" => 9],
            ["id" => 91, "name" => "Artemisa", "province_id" => 9],
            ["id" => 92, "name" => "Bahía Honda", "province_id" => 9],
            ["id" => 93, "name" => "Bauta", "province_id" => 9],
            ["id" => 94, "name" => "San Antonio de los Baños", "province_id" => 9],
            ["id" => 95, "name" => "Candelaria", "province_id" => 9],
            ["id" => 96, "name" => "Alquizar", "province_id" => 9],
            ["id" => 97, "name" => "Amancio", "province_id" => 10],
            ["id" => 98, "name" => "Puerto Padre", "province_id" => 10],
            ["id" => 99, "name" => "Majibacoa", "province_id" => 10],
            ["id" => 100, "name" => "Jesús Menéndez", "province_id" => 10],
            ["id" => 101, "name" => "Manatí", "province_id" => 10],
            ["id" => 102, "name" => "Las Tunas", "province_id" => 10],
            ["id" => 103, "name" => "Jobabo", "province_id" => 10],
            ["id" => 104, "name" => "Colombia", "province_id" => 10],
            ["id" => 105, "name" => "Colón", "province_id" => 11],
            ["id" => 106, "name" => "Unión de Reyes", "province_id" => 11],
            ["id" => 107, "name" => "Calimete", "province_id" => 11],
            ["id" => 108, "name" => "Jovellanos", "province_id" => 11],
            ["id" => 109, "name" => "Cárdenas", "province_id" => 11],
            ["id" => 110, "name" => "Matanzas", "province_id" => 11],
            ["id" => 111, "name" => "Los Arabos", "province_id" => 11],
            ["id" => 112, "name" => "Perico", "province_id" => 11],
            ["id" => 113, "name" => "Martí", "province_id" => 11],
            ["id" => 114, "name" => "Limonar", "province_id" => 11],
            ["id" => 115, "name" => "Ciénaga de Zapata", "province_id" => 11],
            ["id" => 116, "name" => "Pedro Betancourt", "province_id" => 11],
            ["id" => 117, "name" => "Jagüey Grande", "province_id" => 11],
            ["id" => 118, "name" => "Bejucal", "province_id" => 12],
            ["id" => 119, "name" => "Jaruco", "province_id" => 12],
            ["id" => 120, "name" => "Santa Cruz del Norte", "province_id" => 12],
            ["id" => 121, "name" => "Nueva Paz", "province_id" => 12],
            ["id" => 122, "name" => "Batabanó", "province_id" => 12],
            ["id" => 123, "name" => "Melena del Sur", "province_id" => 12],
            ["id" => 124, "name" => "Güines", "province_id" => 12],
            ["id" => 125, "name" => "Quivicán", "province_id" => 12],
            ["id" => 126, "name" => "San José de las Lajas", "province_id" => 12],
            ["id" => 127, "name" => "San Nicolás", "province_id" => 12],
            ["id" => 128, "name" => "Madruga", "province_id" => 12],
            ["id" => 129, "name" => "Sandino", "province_id" => 13],
            ["id" => 130, "name" => "San Juan y Martínez", "province_id" => 13],
            ["id" => 131, "name" => "Guane", "province_id" => 13],
            ["id" => 132, "name" => "Consolación del Sur", "province_id" => 13],
            ["id" => 133, "name" => "Los Palacios", "province_id" => 13],
            ["id" => 134, "name" => "San Luis", "province_id" => 13],
            ["id" => 135, "name" => "Minas de Matahambre", "province_id" => 13],
            ["id" => 136, "name" => "Mantua", "province_id" => 13],
            ["id" => 137, "name" => "Viñales", "province_id" => 13],
            ["id" => 138, "name" => "Pinar del Río", "province_id" => 13],
            ["id" => 139, "name" => "La Palma", "province_id" => 13],
            ["id" => 140, "name" => "Jatibonico", "province_id" => 14],
            ["id" => 141, "name" => "Sancti Spíritus", "province_id" => 14],
            ["id" => 142, "name" => "Fomento", "province_id" => 14],
            ["id" => 143, "name" => "Yaguajay", "province_id" => 14],
            ["id" => 144, "name" => "La Sierpe", "province_id" => 14],
            ["id" => 145, "name" => "Cabaiguán", "province_id" => 14],
            ["id" => 146, "name" => "Trinidad", "province_id" => 14],
            ["id" => 147, "name" => "Taguasco", "province_id" => 14],
            ["id" => 148, "name" => "Songo La Maya", "province_id" => 15],
            ["id" => 149, "name" => "Contramaestre", "province_id" => 15],
            ["id" => 150, "name" => "Tercer Frente", "province_id" => 15],
            ["id" => 151, "name" => "Julio Antonio Mella", "province_id" => 15],
            ["id" => 152, "name" => "San Luis", "province_id" => 15],
            ["id" => 153, "name" => "Segundo Frente", "province_id" => 15],
            ["id" => 154, "name" => "Santiago de Cuba", "province_id" => 15],
            ["id" => 155, "name" => "Palma Soriano", "province_id" => 15],
            ["id" => 156, "name" => "Guamá", "province_id" => 15],
            ["id" => 157, "name" => "Ranchuelo", "province_id" => 16],
            ["id" => 158, "name" => "Caibarién", "province_id" => 16],
            ["id" => 159, "name" => "Santa Clara", "province_id" => 16],
            ["id" => 160, "name" => "Quemado de Güines", "province_id" => 16],
            ["id" => 161, "name" => "Placetas", "province_id" => 16],
            ["id" => 162, "name" => "Camajuaní", "province_id" => 16],
            ["id" => 163, "name" => "Sagua la Grande", "province_id" => 16],
            ["id" => 164, "name" => "Santo Domingo", "province_id" => 16],
            ["id" => 165, "name" => "Remedios", "province_id" => 16],
            ["id" => 166, "name" => "Corralillo", "province_id" => 16],
            ["id" => 167, "name" => "Cifuentes", "province_id" => 16],
            ["id" => 168, "name" => "Manicaragua", "province_id" => 16],
            ["id" => 169, "name" => "Encrucijada", "province_id" => 16],
            ["id" => 226, "name" => "test", "province_id" => 19],
        ];

        foreach ($municipalities as $municipality) {
            $province = Province::find($municipality['province_id']);
            if ($province) {
                Municipality::firstOrCreate(
                    ['id' => $municipality['id']],
                    [
                        'name' => $municipality['name'],
                        'province_id' => $municipality['province_id'],
                    ]
                );
            }
        }
    }
}
